[tool.poetry]
name = "atcoder"
version = "0.1.0"
description = ""
authors = ["Yuta Takahashi"]

[tool.poetry.dependencies]
python = "3.8.2"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
